from fastapi import APIRouter, HTTPException, Depends
from pydantic import BaseModel
from sqlalchemy.orm import Session
from database import SessionLocal, Document, init_db
from fpdf import FPDF
from datetime import datetime
import tempfile, os, traceback
from fastapi.responses import FileResponse

router = APIRouter()

# ----------------------------
# DB Session Dependency
# ----------------------------
def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()

# ----------------------------
# Request Schema
# ----------------------------
class SaveRequest(BaseModel):
    title: str
    content: str
    user_id: str | None = None

# ----------------------------
# Save Document + Generate Styled PDF (Unicode Safe with Bold & Italic)
# ----------------------------
@router.post("/")
async def save_document(req: SaveRequest, db: Session = Depends(get_db)):
    try:
        init_db()

        if not req.title.strip() or not req.content.strip():
            raise ValueError("Title and content cannot be empty.")

        # ✅ Save to DB
        new_doc = Document(
            title=req.title,
            content=req.content,
            user_id=req.user_id,
        )
        db.add(new_doc)
        db.commit()
        db.refresh(new_doc)

        # ✅ Font directory setup
        FONT_DIR = os.path.join(os.path.dirname(__file__), "../fonts")
        os.makedirs(FONT_DIR, exist_ok=True)
        FONT_REGULAR = os.path.join(FONT_DIR, "DejaVuSans.ttf")
        FONT_BOLD = os.path.join(FONT_DIR, "DejaVuSans-Bold.ttf")
        FONT_ITALIC = os.path.join(FONT_DIR, "DejaVuSans-Oblique.ttf")

        # ✅ Font existence check
        for font_file in [FONT_REGULAR, FONT_BOLD, FONT_ITALIC]:
            if not os.path.exists(font_file):
                print(f"⚠️ Missing font file: {font_file}")
                raise FileNotFoundError(
                    "DejaVuSans.ttf / DejaVuSans-Bold.ttf / DejaVuSans-Oblique.ttf missing in backend/fonts/"
                )

        # ✅ Create styled PDF with consistent name
        pdf_dir = tempfile.gettempdir()
        pdf_path = os.path.join(pdf_dir, f"doc_{new_doc.id}.pdf")

        pdf = FPDF()
        pdf.add_page()

        # Add Unicode fonts (Regular, Bold, Italic)
        pdf.add_font("DejaVu", "", FONT_REGULAR, uni=True)
        pdf.add_font("DejaVu", "B", FONT_BOLD, uni=True)
        pdf.add_font("DejaVu", "I", FONT_ITALIC, uni=True)

        # ----------------------------
        # Header Section
        # ----------------------------
        pdf.set_fill_color(28, 33, 48)  # Dark header background
        pdf.rect(0, 0, 210, 25, "F")
        pdf.set_text_color(255, 255, 255)
        pdf.set_font("DejaVu", "B", 16)
        pdf.cell(0, 15, "LawHelpZone AI — Legal Document", ln=True, align="C")
        pdf.ln(10)

        # ----------------------------
        # Document Info
        # ----------------------------
        pdf.set_text_color(0, 0, 0)
        pdf.set_font("DejaVu", "", 12)
        pdf.cell(0, 10, f"📄 Document Title: {req.title}", ln=True)
        pdf.cell(0, 10, f"🕒 Created on: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}", ln=True)
        if req.user_id:
            pdf.cell(0, 10, f"👤 Created by: {req.user_id}", ln=True)
        pdf.ln(6)

        # ----------------------------
        # Divider Line
        # ----------------------------
        pdf.set_draw_color(180, 180, 180)
        pdf.set_line_width(0.3)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(8)

        # ----------------------------
        # Content Section
        # ----------------------------
        pdf.set_font("DejaVu", "", 11)
        pdf.multi_cell(0, 8, req.content)
        pdf.ln(12)

        # ----------------------------
        # Signature Placeholder
        # ----------------------------
        pdf.set_font("DejaVu", "I", 11)
        pdf.cell(0, 10, "_________________________", ln=True)
        pdf.cell(0, 8, "Authorized Signature", ln=True)
        pdf.ln(8)

        # ----------------------------
        # Footer Watermark
        # ----------------------------
        pdf.set_y(-15)
        pdf.set_font("DejaVu", "I", 9)
        pdf.set_text_color(120)
        pdf.cell(
            0, 10, "Generated by LawHelpZone AI — www.lawhelpzone.com", 0, 0, "C"
        )

        pdf.output(pdf_path)

        print(f"✅ Saved document and generated styled PDF: {pdf_path}")
        return {
            "status": "success",
            "message": "Document saved and styled PDF generated successfully",
            "id": new_doc.id,
            "pdf_path": pdf_path,
        }

    except Exception as e:
        traceback.print_exc()
        raise HTTPException(status_code=500, detail=f"Error saving document: {str(e)}")


# ----------------------------
# List Documents
# ----------------------------
@router.get("/list")
async def list_documents(user_id: str | None = None, db: Session = Depends(get_db)):
    try:
        init_db()
        query = db.query(Document)
        if user_id:
            query = query.filter(Document.user_id == user_id)
        docs = query.order_by(Document.id.desc()).all()

        print(f"📄 Fetched {len(docs)} documents for user {user_id or 'guest'}")
        return {
            "documents": [
                {
                    "id": d.id,
                    "title": d.title,
                    "content": d.content,
                    "created_at": d.created_at.strftime("%b %d, %Y"),
                }
                for d in docs
            ]
        }
    except Exception as e:
        traceback.print_exc()
        raise HTTPException(status_code=500, detail=f"Error fetching documents: {str(e)}")


# ----------------------------
# Delete Document
# ----------------------------
@router.delete("/delete/{doc_id}")
async def delete_document(doc_id: int, db: Session = Depends(get_db)):
    try:
        init_db()
        doc = db.query(Document).filter(Document.id == doc_id).first()
        if not doc:
            raise HTTPException(status_code=404, detail="Document not found")

        db.delete(doc)
        db.commit()
        print(f"🗑️ Deleted document ID {doc_id}")
        return {"status": "deleted", "id": doc_id}
    except Exception as e:
        traceback.print_exc()
        raise HTTPException(status_code=500, detail=f"Error deleting document: {str(e)}")


# ----------------------------
# Serve PDF
# ----------------------------
@router.get("/pdf/{doc_id}")
async def get_pdf(doc_id: int, db: Session = Depends(get_db)):
    """Serve generated PDF file for viewing or download."""
    init_db()
    doc = db.query(Document).filter(Document.id == doc_id).first()
    if not doc:
        raise HTTPException(status_code=404, detail="Document not found")

    pdf_path = os.path.join(tempfile.gettempdir(), f"doc_{doc_id}.pdf")
    if not os.path.exists(pdf_path):
        raise HTTPException(status_code=404, detail="PDF not found")

    print(f"📄 Serving PDF for document ID {doc_id}: {pdf_path}")
    return FileResponse(pdf_path, media_type="application/pdf")
